services:
  student01:
    build: ./services/student01
    container_name: student01
    ports:
      - "8101:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 5
  student03:
    build: ./Services/student03
    container_name: student03
    ports:
      - "8103:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 5
  student09:
    build: ./services/student09
    container_name: student09
    ports:
      - "8109:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 5